### ISSUE TITLE
can't use two instances on the same webpage

### ISSUE THREAD

**Issue by tracid303** [morgansson/g-scrolling-carousel#4]
Love the code, however i can't seem to use two carousel's (or more) on the same webpage. Only the last carousel will work with the first carousel one not moving. Is there a work around to this?

Cheers :)

**Comment by DustinGT** [comment]
I have the same issue, but you need to do is calling the gScrollingCarousel function like this
$("#carousel1 .items").gScrollingCarousel(); 
$("#carousel2 .items").gScrollingCarousel(); 
and on the items div use
<div id="carousel1" class="g-scrolling-carousel">
...
</div>

<div id="carousel2" class="g-scrolling-carousel">
...
</div>

Hope helps.

**Comment by morgansson** [comment]
This has been fixed on the last release, you can use multiple carousels with the same class and call it only once.
